version: 2.1

jobs:
  build:
    docker:
    - image: jdrouet/docker-with-buildx:stable
    steps:
    - checkout
    - setup_remote_docker:
        version: 18.09.3
    - run:
        name: Update Environment Variables at Runtime
        command: |
          echo 'export PROJECT_NAME=smartthings-nodeproxy' >> $BASH_ENV
          source $BASH_ENV
    - run:
        echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin

    # build the application image
    - run:
        working_directory: smartthings-nodeproxy
        command: |
          docker buildx build --push \
                    --platform linux/amd64 \
                    --tag $DOCKER_ORG/$PROJECT_NAME:latest . -f Dockerfile

workflows:
  version: 2
  build-deploy:
    jobs:
    - build:
        context: global
