version: 2.1

orbs:
  kube-orb: circleci/kubernetes@0.11.0

jobs:
  build:
    machine: true
    steps:

    - checkout

    - run:
        name: Update Environment Variables at Runtime
        command: |
          echo 'export PROJECT_NAME=smartthings-nodeproxy' >> $BASH_ENV
          source $BASH_ENV
    - run:
        echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin

    # build the application image
    - run:
        working_directory: smartthings-nodeproxy
        command: |
          docker build -t $DOCKER_ORG/$PROJECT_NAME-x86_64:$CIRCLE_SHA1 -t $DOCKER_ORG/$PROJECT_NAME-x86_64:latest . -f Dockerfile

    # deploy the image
    - run: |
        docker push $DOCKER_ORG/$PROJECT_NAME-x86_64:$CIRCLE_SHA1 &&
        docker push $DOCKER_ORG/$PROJECT_NAME-x86_64:latest

workflows:
  version: 2
  build-deploy:
    jobs:
    - build:
        context: global
